### ISSUE TITLE
Incompatibility with OpenSSL 3

### ISSUE THREAD

**Issue by whitslack** [Simplexum/python-bitcointx#76]
When OpenSSL 3 is installed, such that `ctypes.util.find_library('ssl')` returns `'libssl.so.3'`, the test suite fails with:
```
======================================================================
ERROR: test_tx_valid (bitcointx.tests.test_transactions.Test_CTransaction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/python-bitcointx-1.1.3/work/python-bitcointx-python-bitcointx-v1.1.3/bitcointx/tests/test_transactions.py", line 296, in test_tx_valid
    VerifyScript(tx.vin[i].scriptSig, prevouts[tx.vin[i].prevout], tx, i, flags=flags)
  File "/var/tmp/portage/dev-python/python-bitcointx-1.1.3/work/python-bitcointx-python-bitcointx-v1.1.3/bitcointx/core/scripteval.py", line 1175, in VerifyScript
    raise VerifyScriptError("scriptPubKey returned false")
bitcointx.core.scripteval.VerifyScriptError: scriptPubKey returned false

======================================================================
FAIL: test_script (bitcointx.tests.test_scripteval.Test_EvalScript)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/python-bitcointx-1.1.3/work/python-bitcointx-python-bitcointx-v1.1.3/bitcointx/tests/test_scripteval.py", line 168, in test_script
    VerifyScript(scriptSig, scriptPubKey, txSpend, 0, flags, amount=nValue, witness=witness)
  File "/var/tmp/portage/dev-python/python-bitcointx-1.1.3/work/python-bitcointx-python-bitcointx-v1.1.3/bitcointx/core/scripteval.py", line 1175, in VerifyScript
    raise VerifyScriptError("scriptPubKey returned false")
bitcointx.core.scripteval.VerifyScriptError: scriptPubKey returned false

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/python-bitcointx-1.1.3/work/python-bitcointx-python-bitcointx-v1.1.3/bitcointx/tests/test_scripteval.py", line 171, in test_script
    self.fail('Script FAILED: %r %r %r with exception %r\n\nTest data: %r' % (scriptSig, scriptPubKey, comment, err, test_case))
AssertionError: Script FAILED: CBitcoinScript([x('304402200060558477337b9022e70534f1fea71a318caf836812465a2509931c5e7c4987022078ec32bd50ac9e03a349ba953dfd9fe1c8d2dd8bdb1d38ddca844d3d5c78c11801')]) CBitcoinScript([x('038282263212c609d9ea2a6e3e172de238d8c39cabd5ac1ca10646e23fd5f51508'), OP_CHECKSIG]) 'P2PK with too much R padding but no DERSIG' with exception VerifyScriptError('scriptPubKey returned false')

Test data: ['0x47 0x304402200060558477337b9022e70534f1fea71a318caf836812465a2509931c5e7c4987022078ec32bd50ac9e03a349ba953dfd9fe1c8d2dd8bdb1d38ddca844d3d5c78c11801', '0x21 0x038282263212c609d9ea2a6e3e172de238d8c39cabd5ac1ca10646e23fd5f51508 CHECKSIG', '', 'OK', 'P2PK with too much R padding but no DERSIG']
```

**Comment by dgpv** [comment]
Will be fixed by #77

**Comment by jonasnick** [comment]
Is this fixed not that  #77 is closed?

**Comment by dgpv** [comment]
Yes, should be fixed, because openssl is not used anymore

**Comment by whitslack** [comment]
Applying a slightly tweaked 737a3f978b38153a6d35128c07b206ad37d6950c gets the tests to pass on Gentoo without OpenSSL 1.1 installed. Thanks.

**Comment by dgpv** [comment]
Seems to be resolved, closing.

**Comment by dgpv** [comment]
I think it was too early to close this issue - it is fixed in master, but not in release. Will now reopen, then close after release of new version.

**Comment by jonasnick** [comment]
Is it possible to make a new release with this issue fixed?

**Comment by dgpv** [comment]
1.1.4 released, closing this.
